pipeline {
  agent any
  tools { nodejs "node" }
  stages {
    stage('Build') {
      steps {
        echo 'Building..'
        echo 'build=${params.build}'
        sh 'npm install'
      }
    }
    stage('Test') {
      steps {
        echo 'Testing..'
        sh 'npm run test'
      }
    }
    stage('Deploy') {
      steps {
        echo 'Deploying....'
        sh 'npm run build'
        sh 'zip -r ngrx-store-example-v5.zip dist/ngrx-store-example-v5/'
      //  sh 'npm publish'
      }
    }
  }
}
